# Based on https://github.com/actions/starter-workflows/blob/main/ci/django.yml

name: Django CI

on:
  push:
    branches: [ master, build_fix ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.8 ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build Docker
        env:
          SECRET_KEY: ${{secrets.SECRET_KEY}}
          SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: ${{secrets.SOCIAL_AUTH_GOOGLE_OAUTH2_KEY}}
          SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: ${{secrets.SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET}}
          ES_PUBLIC_API_KEY: ${{secrets.ES_PUBLIC_API_KEY}}
          ES_COURSE_SEARCH_ENDPOINT: ${{secrets.ES_COURSE_SEARCH_ENDPOINT}}
          ES_INSTRUCTOR_SEARCH_ENDPOINT: ${{secrets.ES_INSTRUCTOR_SEARCH_ENDPOINT}}
          DB_NAME: ${{secrets.DB_NAME}}
          DB_HOST: ${{secrets.DB_HOST}}
          DB_USER: ${{secrets.DB_USER}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
          DB_PORT: ${{secrets.DB_PORT}}
        run: |
          cp .env.example .env
#          touch .env
#          echo "SECRET_KEY=$SECRET_KEY" >> .env
#          echo "SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=$SOCIAL_AUTH_GOOGLE_OAUTH2_KEY" >> .env
#          echo "SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=$SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET" >> .env
#          echo "ES_PUBLIC_API_KEY=$ES_PUBLIC_API_KEY" >> .env
#          echo "ES_COURSE_SEARCH_ENDPOINT=$ES_COURSE_SEARCH_ENDPOINT" >> .env
#          echo "ES_INSTRUCTOR_SEARCH_ENDPOINT=$ES_INSTRUCTOR_SEARCH_ENDPOINT" >> .env
#          echo "DB_NAME=$DB_NAME" >> .env
#          echo "DB_HOST=$DB_HOST" >> .env
#          echo "DB_USER=$DB_USER" >> .env
#          echo "DB_PASSWORD=$DB_PASSWORD" >> .env
#          echo "DB_PORT=$DB_PORT" >> .env
          docker build .
          docker-compose up -d
      - name: Run Tests
        run: |
          docker exec tcf_django python3 manage.py test