name: Test

on:
  push:
    branches: [master]

  workflow_run:
    workflows: ["Echo"]
    branches: [dev]
    types:
      - completed

jobs:
  success:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: echo success
        run: echo success
        shell: bash
  failure:
    if: ${{ github.event.workflow_run.conclusion != 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: echo failure
        run: echo failure
        shell: bash
